apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
# This is a hashed string, not encrypted. As such, we should consider this
# the same as a cleartext password. Committing passwords into repositories
# is a big no-no and is done here for sharing the exercise solution
  DB_PASSWORD: d293aW1zb3NlY3VyZQ==